'android.provider.Settings Constants, for more Settings Constants, please refer https://developer.android.google.cn/reference/android/provider/Settings.html .\n\nYou can use them like droid.startActivity(droid.provider.Settings.ACTION_SETTINGS) .'

ACTION_SETTINGS='android.settings.SETTINGS'
ACTION_SOUND_SETTINGS='android.settings.SOUND_SETTINGS'
ACTION_WIRELESS_SETTINGS='android.settings.WIRELESS_SETTINGS'
ACTION_APPLICATION_SETTINGS='android.settings.APPLICATION_SETTINGS'
ACTION_BLUETOOTH_SETTINGS='android.settings.BLUETOOTH_SETTINGS'
ACTION_CAPTIONING_SETTINGS='android.settings.CAPTIONING_SETTINGS'
ACTION_DATA_USAGE_SETTINGS='android.settings.DATA_USAGE_SETTINGS'
ACTION_DATE_SETTINGS='android.settings.DATE_SETTINGS'
ACTION_DEVICE_INFO_SETTINGS='android.settings.DEVICE_INFO_SETTINGS'
ACTION_DISPLAY_SETTINGS='android.settings.DISPLAY_SETTINGS'
ACTION_HARD_KEYBOARD_SETTINGS='android.settings.HARD_KEYBOARD_SETTINGS'
ACTION_INPUT_METHOD_SETTINGS='android.settings.INPUT_METHOD_SETTINGS'
ACTION_INTERNAL_STORAGE_SETTINGS='android.settings.INTERNAL_STORAGE_SETTINGS'
ACTION_LOCALE_SETTINGS='android.settings.LOCALE_SETTINGS'
ACTION_LOCATION_SOURCE_SETTINGS='android.settings.LOCATION_SOURCE_SETTINGS'
ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS='android.settings.IGNORE_BATTERY_OPTIMIZATION_SETTINGS'
ACTION_BATTERY_SAVER_SETTINGS="android.settings.BATTERY_SAVER_SETTINGS"
ACTION_ACCESSIBILITY_SETTINGS = "android.settings.ACCESSIBILITY_SETTINGS"
ACTION_AIRPLANE_MODE_SETTINGS = "android.settings.AIRPLANE_MODE_SETTINGS"
